"""empty message

Revision ID: f0f3df9e3c64
Revises: fb11536e1e4b
Create Date: 2024-04-20 22:02:02.818616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0f3df9e3c64'
down_revision = 'fb11536e1e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Catalog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Catalog', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('image')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
